### PR TITLE
Added runnable demo module

### PR DESCRIPTION
**Pull request by MarkOSullivan94**
**Problem**
As highlighted by issue #42 there is no demo within the project to allow people to quickly try out some of the features of Notils.

**Solution**
I've added a demo module which will allow everyone who is curious about the project to clone it and quickly run it to test out some of the features.

Currently it is limited with only two features but I felt it would be best opening a PR with one feature done before adding more, plus it leaves a foundation for others to be able to quickly build upon.

### CODE REVIEW

**Comment by hal9002** [comment]
Can one of the admins review this PR?

**Comment by MarkOSullivan94** [comment]
@asomaniac @danybony @ouchadam can one of you give feedback for this PR please?

**Review by blundell — APPROVED** [review]
nice! Thanks for taking the time, I really like the readme with the check boxes

**Comment by MarkOSullivan94** [comment]
Thank you!

**Review by joetimmins — APPROVED** [review]

**Comment by tasomaniac** [comment]
Nice :+1:

**Comment by ataulm** [comment]
Thanks for listing the features too - handy to have them in one place so we know what's left 🙏

**Comment by MarkOSullivan94** [comment]
It would probably be a good idea to assign an issue for each item you want done in the list, means people can say they're working on it so there isn't multiple people working on the same feature.

Also thanks @joetimmins for merging it in!

**Pull request merged**
