### PR TITLE
TextWatcher simple implementation

### PR DESCRIPTION
**Pull request by danybony**
> I don't really care about beforeTextChanged or onTextChanged.
> I only need the good old **afterTextChanged**!
>
> -- *<cite>An Android developer</cite>*

### CODE REVIEW

**Comment by stefanhoth** [comment]
I'd say this addition is of questionable value. While it surely moves the no-op impls to Notils, making the code seem cleaner it might add some confusion for devs who know the interface, wondering where the rest of the events go.

I think the benefit of having this in Notils is very marginal.

**Comment by blundell** [comment]
but tbf everytime I use this interface I only want one of the 3 methods so :+1: from me

**Comment by danybony** [comment]
@stefanhoth this is open to discussion. 
It is a thing I saw in several projects and I always though it could have been useful to have in Notils.
Regarding the `confusion for devs who know the interface` I'd say that this is way less confusing than our  `logger` implementation compared to the `android.util` one.

**Comment by malmstein** [comment]
:+1: from me as well. Death to no-ops!

**Comment by friedger** [comment]
:x: needs an update of the readme

@danybony The argument that there are other confusing APIs does not count :-)

Happy with it as proguard removes the class if not needed.

**Comment by danybony** [comment]
@friedger readme updated!

**Comment by friedger** [comment]
:+1: Letting @stefanhoth merge it

**Comment by stefanhoth** [comment]
I wouldn't X it but I still don't see the big benefit and would rather have this No-op base class in my own project. But if @malmstein or @blundell are big fans they should merge it.

**Comment by blundell** [comment]
:angel:

**Comment by malmstein** [comment]
:dancer:

**Pull request merged**
