### PR TITLE
Inherit from Error instead of RuntimeException.

### PR DESCRIPTION
**Pull request by HenriqueRocha**
According to the Java semantics of Exceptions:
>The class Exception and its subclasses are a form of Throwable that indicates conditions that a reasonable application might want to catch.

Instead, the semantics of Error are as following:
> An Error is a subclass of Throwable that indicates serious problems that a reasonable application should not try to catch. Most such errors are abnormal conditions.

### CODE REVIEW

**Comment by xrigau** [comment]
:+1: seems legit

**Comment by grujo** [comment]
:+1:

**Comment by friedger** [comment]
With so many :+1: I just merge it.

**Comment by blundell** [comment]
:+1:

**Pull request merged**
