### PR TITLE
DeveloperError is a final class

### PR DESCRIPTION
**Pull request by joetimmins**
As title says.... DeveloperError is now a final class. Based on this issue https://github.com/novoda/notils/issues/51

### CODE REVIEW

**Comment by ataulm** [comment]
I'm happy either way - I closed the issue this is based on (sorry @joetimmins I promise I'm not waiting til you open PRs just to invalidate the stories :grin:)

For me if you're extending this class, you're doing something wrong.

**Comment by takecare** [comment]
`public class SeniorDeveloperError extends DeveloperError`

**Comment by ataulm** [comment]
Hahaha

On Wed, 27 Apr 2016, 19:12 Rui Teixeira, <notifications@github.com> wrote:

> public class SeniorDeveloperError extends DeveloperError
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/novoda/notils/pull/73#issuecomment-215177488>
>

-- 
Disclaimer: The information in this e-mail and any attachments is the 
property of Novoda Ltd and is confidential and may be legally privileged. 
This e-mail is intended solely for the person or organisation to which it 
is addressed. Any disclosure, copying or other use of the information by 
any person or organisation who is not the intended recipient is strictly 
prohibited and may be unlawful. If you have received this e-mail in error, 
please inform the sender immediately and delete/destroy this e-mail and any 
copies of it. Novoda Ltd has taken reasonable precautions to minimise the 
risk of any software viruses which may damage your systems, but we advise 
that you take the necessary steps to ensure that no virus contamination is 
suffered. Novoda Ltd does not accept any liability for any loss or damage 
caused by the transmission of any virus.

Novoda Ltd, Company No: 347444, Registered in Scotland Registered 
Office: C/O Alexander Sloan, 38 Cadogan Street, Glasgow, G2 7HF, Scotland.  VAT 
Registration Number  GB 984 2525 93

**Comment by fourlastor** [comment]
Shall we merge? @ataulm anything against merging?

**Comment by ataulm** [comment]
Yep happy for this to be merged.

**Comment by blundell** [comment]
come on, after all the chat I thought the answer was to not do this :D haha oh well, won the battle lost the war!

**Pull request merged**
